name: PerWorldPlayer
main: BlockHorizons\PerWorldPlayer\Loader
api: 5.0.0
version: 0.4.7

permissions:
  per-world-player.bypass:
    default: false
    description: Allows bypassing the per world player.
